# Generated by Django 5.0.6 on 2024-06-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default='default_property.jpg', upload_to='property'),
        ),
    ]
